-- Seed Data for Connect to Lecturer Feature
-- Sample lecturer profiles across different faculties

-- Note: Replace the user_id with actual user IDs from your profiles table
-- For now, using placeholder UUIDs that you should update

-- Insert sample lecturers
INSERT INTO lecturer_profiles (
  user_id,
  title,
  full_name,
  email,
  phone,
  faculty,
  department,
  subjects,
  office_location,
  availability,
  bio,
  photo_url,
  rating,
  total_ratings,
  is_active,
  is_verified
) VALUES
-- Engineering Faculty
(
  gen_random_uuid(),
  'Prof.',
  'Sarah Nkosi',
  'sarah.nkosi@university.ac.za',
  '+27 21 123 4567',
  'engineering',
  'Computer Science',
  ARRAY['Data Structures', 'Algorithms', 'Artificial Intelligence', 'Machine Learning'],
  'Engineering Building, Room 301',
  'Mon-Fri, 9AM-5PM',
  'Professor of Computer Science with 15 years of experience in AI and machine learning. Passionate about helping students understand complex algorithms.',
  'https://i.pravatar.cc/150?img=1',
  4.8,
  156,
  true,
  true
),
(
  gen_random_uuid(),
  'Dr.',
  'Thabo Mokoena',
  'thabo.mokoena@university.ac.za',
  '+27 21 123 4568',
  'engineering',
  'Electrical Engineering',
  ARRAY['Circuit Theory', 'Power Systems', 'Control Systems'],
  'Engineering Building, Room 205',
  'Tue-Thu, 10AM-4PM',
  'Electrical Engineering specialist focusing on renewable energy systems and smart grids.',
  'https://i.pravatar.cc/150?img=13',
  4.6,
  89,
  true,
  true
),

-- Science Faculty
(
  gen_random_uuid(),
  'Dr.',
  'Michael van der Merwe',
  'michael.vandermerwe@university.ac.za',
  '+27 21 123 4569',
  'science',
  'Physics',
  ARRAY['Quantum Mechanics', 'Thermodynamics', 'Classical Mechanics'],
  'Science Building, Room 402',
  'Tue-Thu, 10AM-4PM',
  'Physics lecturer with expertise in quantum mechanics. Available for consultation on research projects.',
  'https://i.pravatar.cc/150?img=12',
  4.9,
  203,
  true,
  true
),
(
  gen_random_uuid(),
  'Prof.',
  'Lindiwe Dube',
  'lindiwe.dube@university.ac.za',
  '+27 21 123 4570',
  'science',
  'Chemistry',
  ARRAY['Organic Chemistry', 'Analytical Chemistry', 'Biochemistry'],
  'Science Building, Room 315',
  'Mon-Wed-Fri, 11AM-3PM',
  'Chemistry professor specializing in organic synthesis and medicinal chemistry.',
  'https://i.pravatar.cc/150?img=9',
  4.7,
  134,
  true,
  true
),

-- Commerce Faculty
(
  gen_random_uuid(),
  'Dr.',
  'Thandiwe Dlamini',
  'thandiwe.dlamini@university.ac.za',
  '+27 21 123 4571',
  'commerce',
  'Accounting',
  ARRAY['Financial Accounting', 'Auditing', 'Taxation', 'Management Accounting'],
  'Commerce Building, Room 201',
  'Mon-Wed, 8AM-2PM',
  'Chartered Accountant with 10 years industry experience. Specializing in financial reporting and auditing.',
  'https://i.pravatar.cc/150?img=5',
  4.7,
  178,
  true,
  true
),
(
  gen_random_uuid(),
  'Prof.',
  'David Chen',
  'david.chen@university.ac.za',
  '+27 21 123 4572',
  'commerce',
  'Economics',
  ARRAY['Microeconomics', 'Macroeconomics', 'Econometrics'],
  'Commerce Building, Room 305',
  'Tue-Thu, 9AM-5PM',
  'Economics professor with research focus on development economics and policy analysis.',
  'https://i.pravatar.cc/150?img=14',
  4.8,
  192,
  true,
  true
),

-- Humanities Faculty
(
  gen_random_uuid(),
  'Prof.',
  'James Smith',
  'james.smith@university.ac.za',
  '+27 21 123 4573',
  'humanities',
  'Psychology',
  ARRAY['Cognitive Psychology', 'Research Methods', 'Developmental Psychology'],
  'Humanities Building, Room 408',
  'Mon-Fri, 11AM-3PM',
  'Clinical psychologist and researcher specializing in cognitive behavioral therapy and mental health.',
  'https://i.pravatar.cc/150?img=15',
  4.6,
  145,
  true,
  true
),
(
  gen_random_uuid(),
  'Dr.',
  'Fatima Hassan',
  'fatima.hassan@university.ac.za',
  '+27 21 123 4574',
  'humanities',
  'Sociology',
  ARRAY['Social Theory', 'Research Methodology', 'Urban Sociology'],
  'Humanities Building, Room 302',
  'Mon-Wed-Fri, 10AM-2PM',
  'Sociologist researching urban development and social inequality in South African cities.',
  'https://i.pravatar.cc/150?img=10',
  4.5,
  98,
  true,
  true
),

-- Health Sciences Faculty
(
  gen_random_uuid(),
  'Dr.',
  'Sipho Ndlovu',
  'sipho.ndlovu@university.ac.za',
  '+27 21 123 4575',
  'health',
  'Medicine',
  ARRAY['Anatomy', 'Physiology', 'Pathology'],
  'Medical School, Room 501',
  'Tue-Thu, 8AM-12PM',
  'Medical doctor and lecturer with 20 years clinical experience. Specializing in internal medicine.',
  'https://i.pravatar.cc/150?img=11',
  4.9,
  267,
  true,
  true
),
(
  gen_random_uuid(),
  'Prof.',
  'Nomsa Khumalo',
  'nomsa.khumalo@university.ac.za',
  '+27 21 123 4576',
  'health',
  'Nursing',
  ARRAY['Clinical Nursing', 'Community Health', 'Nursing Ethics'],
  'Nursing Building, Room 203',
  'Mon-Wed-Fri, 9AM-3PM',
  'Registered nurse and educator with expertise in community health and primary healthcare.',
  'https://i.pravatar.cc/150?img=47',
  4.8,
  189,
  true,
  true
),

-- Law Faculty
(
  gen_random_uuid(),
  'Prof.',
  'John Williams',
  'john.williams@university.ac.za',
  '+27 21 123 4577',
  'law',
  'Law',
  ARRAY['Constitutional Law', 'Criminal Law', 'Human Rights Law'],
  'Law Building, Room 401',
  'Tue-Thu, 10AM-4PM',
  'Advocate and law professor specializing in constitutional and human rights law.',
  'https://i.pravatar.cc/150?img=33',
  4.7,
  156,
  true,
  true
),
(
  gen_random_uuid(),
  'Dr.',
  'Zanele Mthembu',
  'zanele.mthembu@university.ac.za',
  '+27 21 123 4578',
  'law',
  'Law',
  ARRAY['Contract Law', 'Commercial Law', 'Company Law'],
  'Law Building, Room 305',
  'Mon-Wed, 11AM-5PM',
  'Commercial law specialist with experience in corporate law and mergers & acquisitions.',
  'https://i.pravatar.cc/150?img=49',
  4.6,
  123,
  true,
  true
),

-- Education Faculty
(
  gen_random_uuid(),
  'Dr.',
  'Peter Botha',
  'peter.botha@university.ac.za',
  '+27 21 123 4579',
  'education',
  'Education',
  ARRAY['Educational Psychology', 'Curriculum Development', 'Teaching Methods'],
  'Education Building, Room 201',
  'Mon-Fri, 9AM-3PM',
  'Education specialist focusing on innovative teaching methods and educational technology.',
  'https://i.pravatar.cc/150?img=52',
  4.5,
  134,
  true,
  true
),

-- Arts & Design Faculty
(
  gen_random_uuid(),
  'Prof.',
  'Ayanda Zulu',
  'ayanda.zulu@university.ac.za',
  '+27 21 123 4580',
  'arts',
  'Fine Arts',
  ARRAY['Drawing', 'Painting', 'Art History', 'Contemporary Art'],
  'Arts Building, Studio 3',
  'Tue-Thu, 10AM-4PM',
  'Contemporary artist and educator with exhibitions across South Africa. Passionate about African art.',
  'https://i.pravatar.cc/150?img=45',
  4.8,
  167,
  true,
  true
),
(
  gen_random_uuid(),
  'Dr.',
  'Maria Santos',
  'maria.santos@university.ac.za',
  '+27 21 123 4581',
  'arts',
  'Graphic Design',
  ARRAY['Typography', 'Digital Design', 'Brand Identity', 'UI/UX Design'],
  'Arts Building, Lab 2',
  'Mon-Wed-Fri, 11AM-5PM',
  'Graphic designer and educator specializing in digital media and user experience design.',
  'https://i.pravatar.cc/150?img=48',
  4.7,
  145,
  true,
  true
);

-- Note: After running this, you should update the user_id values to match actual user IDs in your profiles table
